Repository Dosilock/Frontend, pull requests merged in 2024-05, with the labels that each got.

#33 이메일 로그인 기능 구현 (#32)
  README.md
Labels: Task

#45 이메일 회원가입 기본 정보 입력 제출 폼 구현
  src/app/signup/[token]/error.tsx
  src/app/signup/[token]/loading.tsx
  src/app/signup/[token]/page.tsx
  src/app/signup/_actions/actions.ts
  src/app/signup/_forms/SignUpForm.tsx
Labels: ✨ Feature, 📬 API

#48 Socket.io 실시간 통신 기능 기본 설정
  package.json
  pnpm-lock.yaml
  src/app/class/[cid]/_handler/SocketHandler.tsx
  src/app/class/[cid]/layout.tsx
  src/socket/SocketEvents.ts
  src/socket/socket.ts
Labels: ⚙ Setting, ✨ Feature

#50 변경된 API 응답 형식 대응
  src/app/class/[cid]/_actions/actions.ts
  src/app/class/[cid]/dashboard/@todayRank/_components/FocusRanking.tsx
  src/app/class/[cid]/error.tsx
  src/app/class/[cid]/layout.tsx
  src/app/class/[cid]/loading.tsx
  src/app/signup/_actions/actions.ts
  src/types/api.ts
  src/utils/apiHelper.ts
Labels: 🔨 Refactor, 📬 API

#52 로그인 화면 폼 제출 관리
  src/app/login/_forms/LoginForm.action.ts
  src/app/login/_forms/LoginForm.tsx
  src/components/SocialLogins/SocialLogins.tsx
  src/components/ui/input.tsx
  src/enums/ActionStatus.ts
  src/static/icons/devicon_google.svg
  src/static/icons/kakao_icon.svg
  src/types/actions.ts
Labels: 🔨 Refactor

#58 SocketHandler RSC 오류 수정
  src/app/class/[cid]/_handler/SocketHandler.tsx
Labels: 🐞 BugFix

#60 반 생성 폼 구조 변경 및 로직 구현
  package.json
  pnpm-lock.yaml
  src/app/class/[cid]/_store/PeriodsStore.ts
  src/app/class/create/_actions/actions.ts
  src/app/class/create/_components/DayOfWeekSelector.tsx
  src/app/class/create/_forms/PeriodForm.tsx
  src/app/class/create/_forms/RequiredForm.tsx
  src/app/class/create/_forms/TemplateForm.tsx
  src/app/class/create/_forms/TimetableDetailForm.tsx
  src/app/class/create/_forms/TimetableForm.tsx
  src/app/class/create/complete/page.tsx
  src/app/class/create/page.tsx
  src/app/class/create/step/_forms/TimetableDetailForm.tsx
  src/app/class/create/step/_forms/TimetableForm.tsx
  src/app/class/create/step/layout.tsx
  src/app/class/create/step/required/page.tsx
  src/app/class/create/step/template/page.tsx
  src/app/class/create/step/timetable-detail/page.tsx
  src/app/class/create/step/timetable/page.tsx
  src/app/class/page.tsx
  src/components/DayOfWeekToggle/DayOfWeekToggle.tsx
Labels: ⚙ Setting, ✨ Feature, 🔨 Refactor, 📬 API, 🐞 BugFix, 🎨 Publishing

#63 Backend API 호출 Server Actions 분리
  .gitignore
  package.json
  pnpm-lock.yaml
  src/app/actions/auth.actions.ts
  src/app/actions/class.actions.ts
  src/app/actions/index.ts
  src/app/actions/timetable.actions.ts
  src/app/actions/users.actions.ts
  src/app/actions/validate.actions.ts
  src/app/login/_forms/LoginForm.tsx
  src/app/login/page.tsx
  src/axios/serverAxios.ts
  src/lib/fetcher.ts
  src/types/actions.ts
  src/types/api.ts
Labels: ⚙ Setting, 🔨 Refactor, 📬 API

#65 배포된 API Endpoint 연결
  src/app/actions/auth.actions.ts
  src/app/actions/class.actions.ts
  src/app/actions/users.actions.ts
  src/app/actions/validate.actions.ts
  src/app/class/create/_actions/actions.ts
  src/app/class/create/complete/not-found.tsx
  src/app/class/create/page.tsx
  src/app/class/page.tsx
  src/app/login/_forms/LoginForm.action.ts
  src/app/reset-password/[token]/page.tsx
  src/app/reset-password/_actions/actions.ts
  src/app/reset-password/_forms/ResetPasswordForm.action.ts
  src/app/reset-password/_forms/ResetPasswordForm.tsx
  src/app/reset-password/_forms/SendResetPasswordMailForm.action.ts
  src/app/reset-password/_forms/SendResetPasswordMailForm.tsx
  src/app/reset-password/page.tsx
  src/app/signup/[token]/page.tsx
  src/app/signup/_actions/actions.ts
  src/app/signup/_forms/SendSignUpMailForm.action.ts
  src/app/signup/_forms/SendSignUpMailForm.tsx
  src/app/signup/_forms/SignUpForm.action.ts
  src/app/signup/_forms/SignUpForm.tsx
  src/app/signup/mail/page.tsx
  src/lib/fetcher.ts
  src/types/clazz.ts
Labels: 🔨 Refactor, 📬 API
